# 原文链接
https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
# 基础
NumPy 处理的主要对象是同类型高维数组。它是有一些相同类型并可以通过元组索引到的元素组成的表。每一维度称为_axes_，axes 的个数称为_rank_。
NumPy 的 array 类是```ndarray```，需要注意的是```numpy.array```和 Python 标准的```array.array```不是同一类数组。

## Example

In [1]:
# 引入 NumPy
import numpy as np

In [2]:
# 创建一个3行5列的二维数组
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.dtype.name

'int64'

In [6]:
a.itemsize

8

In [7]:
a.size

15

In [8]:
type(a)

numpy.ndarray

In [9]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [10]:
type(b)

numpy.ndarray

## 创建数组
NumPy 有很多种方法创建矩阵：
* 通过 Python 的 array 创建

In [11]:
a = np.array([1,2,3,4]) # 创建一维数组
a

array([1, 2, 3, 4])

In [12]:
b = np.array([(1.5,2,3), (4,5,6)]) # 创建二维数组
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [13]:
c = np.array([[1,2],[3,4]], dtype=complex) # 创建二维复数矩阵
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

* 通过 NumPy 创建

In [14]:
np.zeros((3,4)) # 创建零矩阵

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [15]:
np.ones((2,3,4), dtype=np.int16) # 创建一矩阵

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [16]:
np.empty((2,3)) # 创建空矩阵，未赋值

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

NumPy 可以通过函数创建矩阵，```arange```和```linspace```会把返回的结果生成一个矩阵。

In [17]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [18]:
from numpy import pi
x = np.linspace(0, 2*pi, 8)
x

array([ 0.        ,  0.8975979 ,  1.7951958 ,  2.6927937 ,  3.5903916 ,
        4.48798951,  5.38558741,  6.28318531])

In [19]:
f = np.sin(x)
f

array([  0.00000000e+00,   7.81831482e-01,   9.74927912e-01,
         4.33883739e-01,  -4.33883739e-01,  -9.74927912e-01,
        -7.81831482e-01,  -2.44929360e-16])