In [1]:
import numpy as np
import tensorflow as tf

In [2]:
sess = tf.InteractiveSession()
data1 = np.array([
    [[1., 0., 0.],[0., 1., 0.],[0., 1., 0.]],
    [[1., 0., 0.],[0., 1., 0.],[0., 1., 0.]],
    [[1., 0., 0.],[1., 0., 0.],[1., 0., 0.]]
])
data2 = np.array([
    [[2.0, 0.2, 0.1],[0., 1., 0.],[0., 1., 0.]],
    [[1., 0., 0.],[0., 1., 0.],[0., 1., 0.]],
    [[1., 0., 0.],[1., 0., 0.],[1., 0., 0.]]
])
data3 = np.array([
    [[0],[1],[1]],
    [[0],[1],[1]],
    [[0],[0],[0]]
])
data4 = np.array([
    [[0],[1],[1]],
    [[0],[1],[1]],
    [[0],[0],[0]]
])
y_true = np.array([data1])
y_pred = np.array([data2])
y_true_p = np.array([data3])
y_pred_p = np.array([data4])
print(y_true.shape)
print(y_pred.shape)
print(y_true_p.shape)
print(y_pred_p.shape)

(1, 3, 3, 3)
(1, 3, 3, 3)
(1, 3, 3, 1)
(1, 3, 3, 1)


In [3]:
# mean_squared_error
r = tf.reduce_mean(tf.square(y_pred - y_true))
print(r.eval())

0.0388888888889


In [4]:
# mean_absolute_error
r = tf.reduce_mean(tf.abs(y_pred - y_true))
print(r.eval())

0.0481481481481


In [5]:
# categorical_crossentropy

In [6]:
# sparse_categorical_crossentropy

In [7]:
temp = tf.one_hot(tf.arg_max(tf.nn.softmax(y_pred), dimension=3), depth=3)
temp = tf.nn.softmax(y_pred)
print(temp.eval())
r = y_true * tf.log(temp)
print(r.eval())
r = -tf.reduce_sum(r)
print(r.eval())

[[[[ 0.7605329   0.12571524  0.11375186]
   [ 0.21194156  0.57611688  0.21194156]
   [ 0.21194156  0.57611688  0.21194156]]

  [[ 0.57611688  0.21194156  0.21194156]
   [ 0.21194156  0.57611688  0.21194156]
   [ 0.21194156  0.57611688  0.21194156]]

  [[ 0.57611688  0.21194156  0.21194156]
   [ 0.57611688  0.21194156  0.21194156]
   [ 0.57611688  0.21194156  0.21194156]]]]
[[[[-0.27373591 -0.         -0.        ]
   [-0.         -0.55144471 -0.        ]
   [-0.         -0.55144471 -0.        ]]

  [[-0.55144471 -0.         -0.        ]
   [-0.         -0.55144471 -0.        ]
   [-0.         -0.55144471 -0.        ]]

  [[-0.55144471 -0.         -0.        ]
   [-0.55144471 -0.         -0.        ]
   [-0.55144471 -0.         -0.        ]]]]
4.68529361721


In [8]:
r = tf.nn.sigmoid_cross_entropy_with_logits(logits=y_pred, labels=y_true)
print(r.eval())

[[[[ 0.12692801  0.79813887  0.74439666]
   [ 0.69314718  0.31326169  0.69314718]
   [ 0.69314718  0.31326169  0.69314718]]

  [[ 0.31326169  0.69314718  0.69314718]
   [ 0.69314718  0.31326169  0.69314718]
   [ 0.69314718  0.31326169  0.69314718]]

  [[ 0.31326169  0.69314718  0.69314718]
   [ 0.31326169  0.69314718  0.69314718]
   [ 0.31326169  0.69314718  0.69314718]]]]


In [9]:
r = tf.nn.softmax_cross_entropy_with_logits(logits=y_pred, labels=y_true)
print(r.eval())

[[[ 0.27373591  0.55144471  0.55144471]
  [ 0.55144471  0.55144471  0.55144471]
  [ 0.55144471  0.55144471  0.55144471]]]


In [10]:
# r = tf.nn.sparse_softmax_cross_entropy_with_logits(logits=y_pred_p, labels=y_true)
# print(r.eval())

In [11]:
# r = tf.nn.weighted_cross_entropy_with_logits(logits=y_pred, labels=y_true)
# print(r.eval())